extends: eslint:recommended

rules:
    comma-dangle: [1, "always-multiline"]
    no-constant-condition: 0
    curly: [1, "multi-line"]
    quotes: 1
    brace-style: [1, "stroustrup"]

env:
    node: true
